// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (migrate, studio, db pull) needs a direct, non-pooled
    // connection — Supabase's transaction pooler doesn't support the
    // prepared statements migrations rely on.
    url: process.env["DIRECT_URL"],
  },
});
